version: '2'

services:

  redmine:
    build:
      context: ./bitnamiredmine
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: RedmineDatabase
      REDMINE_DB_PORT: 3308
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
      #REDMINE_NO_DB_MIGRATE: 1
    depends_on:
      - RedmineDatabase

  RedmineDatabase:
    image: mysql:5.7
    restart: always
    ports:
      - 3308:3308
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
      MYSQL_TCP_PORT: 3308
    volumes:
      - 'RedmineDB:/var/lib/mysql/'

  Testlink:
    image: bitnami/testlink
    ports:
      - 80:8080
      - 443:8443
    environment:
      - TESTLINK_DATABASE_HOST=TestLinkDatabase
        #- TESTLINK_DATABASE_PORT_NUMBER=3307
      - TESTLINK_DATABASE_USER=root
      - TESTLINK_DATABASE_NAME=testlink
      - TESTLINK_DATABASE_PASSWORD=example
    volumes:
      - 'TestlinkData:/bitnami/testlink'
    depends_on:
      - TestLinkDatabase

  TestLinkDatabase:
    image: mysql:5.7
    restart: always
    #ports:
    #  - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testlink
      # MYSQL_TCP_PORT: 3307
    volumes:
      - 'TestlinkDB:/var/lib/mysql/'


volumes:
  RedmineDB:
    driver: local
  TestlinkDB:
    driver: local
  TestlinkData:
    driver: local

